name: whatsappndt1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8
  emoji_picker_flutter: ^4.3.0

  # Camera & Media
  camera: ^0.11.0
  image_picker: ^1.1.2
  video_player: ^2.7.0
  path_provider: ^2.1.2
  path: ^1.8.3
  file_picker: ^8.0.0

  # Network & Storage
  http: ^1.4.0
  socket_io_client: ^3.1.2
  shared_preferences: ^2.4.10
  flutter_secure_storage: ^9.2.2
  geolocator: ^12.0.0

  # Utils
  logger: ^2.4.0
  permission_handler: ^12.0.1
  otp_text_field: ^1.1.3
  email_validator: ^2.1.17
  url_launcher: ^6.3.0
  timeago: ^3.7.0 # THÊM THƯ VIỆN NÀY

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
